/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import chatsystemproject.ClientThread;
import chatsystemproject.User;
import Database.Connect;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;

/**
 *
 * @author Maeln
 */
public class applicationWindow extends javax.swing.JFrame {

    /**
     * Creates new form applicationWindow
     */
    DefaultListModel dlm = new DefaultListModel();
    private ArrayList<SessionWindow> sessionStarted = new ArrayList<SessionWindow>();
    ClientThread clientThread = null;
    private int mouseX;
    private int mouseY;
    
    private Connect chatSystemDB = null;
                                private static String pathToAdd = "/ChatSystemProject2/chatSystem.db";

    public applicationWindow(ClientThread clientThread, Connect chatSystemDB) {
        
        initComponents();
        
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1,1,1, Color.BLACK));
        this.clientThread = clientThread;
        userPseudo.setText(this.clientThread.getMainUserPseudo());
        System.out.println("Application set");
        this.chatSystemDB = chatSystemDB;
       
        
               
    }
    
    //add to the list
    
    public void updatePseudo(){
        System.out.println("update pseudo :"+this.clientThread.getMainUserPseudo());
        userPseudo.setText(this.clientThread.getMainUserPseudo());
    }
    public void updateUsersList(){
        System.out.println("UPDATE LIST");
        dlm.clear();
        
        ArrayList<User> users = this.clientThread.getMainSystem().getClientList();
         
        Iterator<User> itr = users.iterator();
        
        while(itr.hasNext()) {
            String element = itr.next().getPseudo();
            System.out.println("pseudo : " + element);
            dlm.addElement(new ImgsNText(element,new ImageIcon("images/man-user.png")));
        }  
        
        UserList.setCellRenderer(new Renderer());
        UserList.setModel(dlm);
        System.out.println("List Updated");
    }
   
    // -------- SETTER AND GETTER -------------
    
    
    public ArrayList<SessionWindow> getSessionStarted(){
        return this.sessionStarted;
    }
    
    public Connect getDB() {
        return this.chatSystemDB;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        reduceButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        headerImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserList = new javax.swing.JList<>();
        userPseudo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ChangePseudoButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(350, 0));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(null);

        reduceButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reduceButton.setText("-");
        reduceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reduceButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reduceButtonMouseEntered(evt);
            }
        });
        headerPanel.add(reduceButton);
        reduceButton.setBounds(310, 0, 20, 29);

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitButton.setText("X");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
        });
        headerPanel.add(exitButton);
        exitButton.setBounds(330, 0, 20, 29);

        headerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/headerimg_app.jpg"))); // NOI18N
        headerImg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerImgMouseDragged(evt);
            }
        });
        headerImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerImgMousePressed(evt);
            }
        });
        headerPanel.add(headerImg);
        headerImg.setBounds(0, 0, 350, 100);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Users connected");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 60, 135, 17);

        UserList.setForeground(new java.awt.Color(0, 51, 204));
        UserList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        UserList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 90, 136, 140);

        userPseudo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPseudo.setFocusable(false);
        userPseudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(userPseudo);
        userPseudo.setBounds(0, 30, 350, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Alexandre Cros - Nedellec Maël © 2019-2020");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 270, 240, 20);

        ChangePseudoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChangePseudoButton.setForeground(new java.awt.Color(51, 102, 255));
        ChangePseudoButton.setText("Change Pseudo");
        ChangePseudoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePseudoButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePseudoButtonMouseEntered(evt);
            }
        });
        jPanel1.add(ChangePseudoButton);
        ChangePseudoButton.setBounds(250, 270, 100, 14);

        jLabel2.setText("send files");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 240, 60, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserListMouseClicked
        // TODO add your handling code here:
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            ArrayList<User> users = this.clientThread.getMainSystem().getClientList();
            if(users.isEmpty()){
                
            }
            else{
                String user_selected = ((ImgsNText)list.getSelectedValue()).getName();
                //String user = dlm.getElementAt(index).get
                System.out.println("user : "+user_selected);
                //Start session here and open the session frame

                Iterator<User> itr = users.iterator();
                while(itr.hasNext()) {
                    User user = itr.next();
                    if(user.getPseudo().equals(user_selected)){
                        for(SessionWindow sess : this.sessionStarted){
                            if(sess.getUser().equals(user_selected)){
                                if(!sess.isVisible()){
                                    sess.setVisible(true);
                                    break;
                                }
                                else{
                                    break;
                                }
                            }
                        }
                        SessionWindow session = new SessionWindow(user, this.clientThread, this.chatSystemDB);
                        this.sessionStarted.add(session);
                        session.setVisible(true);
                        session.setLocationRelativeTo(null);
                    }
                }
            }
            
        }
    }//GEN-LAST:event_UserListMouseClicked
    
    // -------- Mouse and Key events -------------
    
    
    private void reduceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_reduceButtonMouseClicked

    private void reduceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceButtonMouseEntered
        reduceButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_reduceButtonMouseEntered

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.clientThread.deletePseudo();
        for(SessionWindow session : this.sessionStarted){
            session.getServerThread().deconnexion();
        }
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void ChangePseudoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePseudoButtonMouseClicked
        String newPseudo = JOptionPane.showInputDialog("Please enter your new pseudo");
        System.out.println("pseudo rentré : "+newPseudo);
        clientThread.changePseudo(newPseudo);
    }//GEN-LAST:event_ChangePseudoButtonMouseClicked

    private void ChangePseudoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePseudoButtonMouseEntered
        ChangePseudoButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ChangePseudoButtonMouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        System.out.println("File choosen : " + filename);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered
// TODO add your handling code here:
    private void headerImgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerImgMousePressed
        this.mouseX = evt.getX();
        this.mouseY = evt.getY();
    }//GEN-LAST:event_headerImgMousePressed

    private void headerImgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerImgMouseDragged
        int cordX = evt.getXOnScreen();
        int cordY = evt.getYOnScreen();
        
        this.setLocation(cordX - mouseX,cordY - mouseY);
    }//GEN-LAST:event_headerImgMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // In a normal way the pseudo is given by the User created before User.getPseudo
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new applicationWindow(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangePseudoButton;
    private javax.swing.JList<String> UserList;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel headerImg;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reduceButton;
    private javax.swing.JLabel userPseudo;
    // End of variables declaration//GEN-END:variables
}
