/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import chatsystemproject.ClientThread;
import chatsystemproject.User;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;

/**
 *
 * @author Maeln
 */
public class pseudoWindow extends javax.swing.JFrame {

    /**
     * Creates new form pseudoWindow
     */
    
    public ClientThread ClThread = null;
    public pseudoWindow(ClientThread ClThread) {
        initComponents();
        this.ClThread = ClThread;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pseudo = new javax.swing.JTextField();
        ValidButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        checkIndication = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("pseudo :");

        pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoActionPerformed(evt);
            }
        });

        ValidButton.setText("Validate");
        ValidButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValidButtonMouseClicked(evt);
            }
        });
        ValidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidButtonActionPerformed(evt);
            }
        });

        checkButton.setText("Check");
        checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkButtonMouseClicked(evt);
            }
        });
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkIndication)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ValidButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkIndication)
                .addGap(49, 49, 49)
                .addComponent(ValidButton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoActionPerformed

    private void ValidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValidButtonActionPerformed

    private void ValidButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValidButtonMouseClicked
        if(checkIndication.getText().equals("Good")){
            // Here we should create the user with the pseudo entered
            this.ClThread.setMainUserPseudo(pseudo.getText());
            applicationWindow aW = new applicationWindow(this.ClThread);
            aW.setVisible(true);
            aW.pack();
            aW.setLocationRelativeTo(null);
            aW.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        else{
            checkIndication.setText("Please enter a valid pseudo");
            Font font = checkIndication.getFont();
            // same font but bold
            Font boldFont = new Font(font.getFontName(), Font.BOLD, font.getSize());
            checkIndication.setFont(boldFont);
        }
    }//GEN-LAST:event_ValidButtonMouseClicked

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkButtonActionPerformed

    private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseClicked
        // TODO add your handling code here:
        
        // In a normal way it calls the method "checkPseudo" to check the unicity, here it is just a test.
        // test if the pseud entered exists in the clientList pseudo (in which we can find the other users pseudo)
        // after all we're using another way to check the unicity.
        boolean check = false;
        String pseud = pseudo.getText();
        ArrayList<User> clientList = this.ClThread.getMainSystem().getClientList();
        
        Iterator<User> itr = clientList.iterator();
        while (itr.hasNext()) {
           String element = itr.next().getPseudo();
           if(pseud.equals(element)){
               check = true;
           }
        }
        if (!check){
            checkIndication.setText("Good");
            checkIndication.setForeground(Color.green);
            
        }
        else if(check) {
            
            checkIndication.setText("Pseudo invalid : "+ pseud);
            checkIndication.setForeground(Color.red);
        }
    }//GEN-LAST:event_checkButtonMouseClicked

    /**
     * @param args the command line arguments/
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pseudoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pseudoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pseudoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pseudoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pseudoWindow(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ValidButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel checkIndication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pseudo;
    // End of variables declaration//GEN-END:variables
}
